### ISSUE TITLE
heroku config:push not working

### ISSUE THREAD

**Issue by fitoprincipe** [Gpzim98/django-heroku#1]
Hello, I was following the tutorial until

`heroku config:push`

> ▸    config:push is not a heroku command.
   ▸    Perhaps you meant config
   ▸    Run heroku help config for a list of available commands.

`heroku help config`

> Flags:
   -a, --app APP        (required) app to run command against
   -r, --remote REMOTE  git remote of app to use
   -s, --shell          output config vars in shell format
   --json               output config vars in json format
   heroku config commands: (get help with heroku help config:COMMAND)
   config          display the config vars for an app
   config:get KEY  display a config value for an app
   config:set      set one or more config vars
   config:unset    unset one or more config vars

**Comment by harsh04** [comment]
heroku plugins:install heroku-config

This may solve your problem

**Comment by Gpzim98** [comment]
This is solved, I've just merged the pull request.
